"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle, ShieldCheck } from "lucide-react";

const FAQS = [
  {
    q: "How does the Multi-Agent System prevent hallucinations?",
    a: "The system enforces strict RAG Reciprocal Rank Fusion (RRF) citations. Every answer generated by the Document and Research Agents includes exact file paths, section numbers, and text snippets with confidence scores. If no document backs a claim, the Supervisor flags it."
  },
  {
    q: "Can the system be deployed 100% on-premise air-gapped?",
    a: "Yes. The backend uses HuggingFace 'all-MiniLM-L6-v2' local zero-cost embeddings, local ChromaDB vector store, and SQLite relational database. It can run seamlessly with local Ollama Llama 3 models without sending data externally."
  },
  {
    q: "How are SQL queries executed safely?",
    a: "The SQL Tool ('sql_tool.py') strictly enforces read-only 'SELECT' query validation using Python AST inspection. Write, update, drop, or alter operations are automatically blocked at the tool layer."
  },
  {
    q: "What types of enterprise data can be ingested?",
    a: "The Universal Document Loader ('app/rag/loaders.py') natively parses Markdown (.md), PDF (.pdf), CSV (.csv), and JSON (.json) files, preserving section titles, category tags, and line offsets."
  },
  {
    q: "How does the Supervisor Agent decide between parallel and sequential routing?",
    a: "The Supervisor analyzes the user request intent. Independent sub-tasks (e.g. querying employee SQL DB + searching RAG documents) are dispatched in parallel via LangGraph. Dependent tasks (e.g. data research -> code evaluation -> PDF synthesis) run sequentially."
  },
  {
    q: "Are the agent tools strictly typed?",
    a: "Yes. All 10 enterprise tools use Pydantic v2 args_schema with strict TypeScript-equivalent validation and return machine-readable JSON payloads."
  }
];

export function FAQAccordion() {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  return (
    <div className="space-y-4 max-w-3xl mx-auto">
      {FAQS.map((faq, idx) => {
        const isOpen = openIdx === idx;
        return (
          <div
            key={idx}
            className={`glass-card rounded-2xl overflow-hidden border transition-all duration-300 ${
              isOpen ? "border-indigo-500/50 bg-slate-900/90 shadow-xl shadow-indigo-500/10" : "border-white/10"
            }`}
          >
            <button
              onClick={() => setOpenIdx(isOpen ? null : idx)}
              className="w-full p-5 text-left flex items-center justify-between gap-4 font-bold text-xs md:text-sm text-white hover:text-indigo-300 transition-colors"
            >
              <span className="flex items-center gap-3">
                <HelpCircle className="w-4 h-4 text-indigo-400 shrink-0" /> {faq.q}
              </span>
              <ChevronDown className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-300 ${isOpen ? "rotate-180 text-indigo-400" : ""}`} />
            </button>

            <AnimatePresence>
              {isOpen && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.3 }}
                >
                  <div className="px-5 pb-5 pt-1 text-xs text-slate-300 leading-relaxed border-t border-white/5 font-normal">
                    {faq.a}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        );
      })}
    </div>
  );
}
